# Permalinks
#
# Github Pages URL : http://mfathirirhas.github.io
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false
excerpt_separator:   _____

# Setup
title:               MFI
tagline:             'mfathirirhas`s blog'
description:         'Sharing things about Computer, Programming, and Technologies.'
url:                 http://mfathirirhas.github.io  #online url
# url:                 http://127.0.0.1:4000  #local url
baseurl:             ''
gems:                [jekyll-paginate, jekyll-gist, jekyll-sitemap]
paginate:            5
paginate_path:       "blog/page:num"
disqus_shortname:    mfathirirhas
facebook_app_id:     164966023945794


# About/contact
author:
  name:              Muhammad Fathir Irhas
  url:               https://twitter.com/FathirIrhas1
  email:             fathir.irhas@outlook.com

# Custom vars
version:             1.0.0

#Social
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
